[Scan.scanner]
camera_firmware = "sony_wifi"
cnc_firmware = "grbl-v1.1"
gimbal_firmware = "blgimbal"

[Scan.scanner.scanner_args] # These are the kwargs passed to the scanner constructor
inverted = false

[Scan.scanner.camera_args] # These are the kwargs passed to the camera constructor
postview = true
device_ip = "10.0.2.66"
api_port = "10000"

[Scan.scanner.cnc_args] # These are kwargs passed to the CNC constructor
homing = true
port = "/dev/ttyUSB0"

[Scan.scanner.gimbal_args]
port = "/dev/ttyACM1"
has_tilt = false
zero_pan = 145

[Scan.scanner.camera_model] # This is a precalibrated camera model
width = 1616
height = 1080
id = 1
model = "OPENCV"
params = [ 1120.72122223961, 1120.72122223961, 808.0, 540.0, 0.0007513494532588769, 0.0007513494532588769, 0.0, 0.0,]

[Scan.scanner.workspace] # A volume containing the target scanned object
x = [ 200, 600,]
y = [ 200, 600,]
z = [ -100, 300,]

[Scan.path] # Example circular scan with 72 points:
type = "circular"

[Scan.path.args]
num_points = 3
radius = 350
tilt = 0.45 # rad
xc = 400
yc = 400
z = 0

[Scan.metadata]
key = value # Any metadata you want to add to the scan

