[Colmap]
upstream_task = "ImagesFilesetExists"

[Undistorted]
upstream_task = "ImagesFilesetExists"

[ModelFileset]
scan_id = "models"

[Segmentation2D]
upstream_task = "Undistorted"
model_fileset = "ModelFileset"
model_id = "Resnetdataset_gl_png_896_896_epoch50" # no default value
query = "{\"channel\":\"rgb\"}" # default {}

[Voxels]
upstream_mask = "Segmentation2D"
upstream_colmap = "Colmap"

[PointCloud]
upstream_task = "Voxels"

[SegmentedPointCloud]
upstream_segmentation = "Segmentation2D"
upstream_task = "PointCloud"

[ClusteredMesh]
upstream_task = "SegmentedPointCloud"

[OrganSegmentation]
upstream_task = "SegmentedPointCloud"

[AnglesAndInternodes]
upstream_task = "ClusteredMesh"

[Visualization]
upstream_point_cloud = "PointCloud"
upstream_mesh = "TriangleMesh"
upstream_colmap = "Colmap"
upstream_angles = "AnglesAndInternodes"
upstream_skeleton = "CurveSkeleton"
upstream_images = "ImagesFilesetExists"