[Colmap]
matcher = "exhaustive"
compute_dense = false

[Colmap.cli_args.feature_extractor]
"--ImageReader.single_camera" = "1"
"--SiftExtraction.use_gpu" = "1"

[Colmap.cli_args.exhaustive_matcher]
"--SiftMatching.use_gpu" = "1"

[Colmap.cli_args.model_aligner]
"--robust_alignment_max_error" = "10"

[accessory]
calibration_scan_id = "calib_scan_shortpath"

[ModelFileset]
scan_id = "models"

[Masks]
upstream_task = "ImagesFilesetExists"
#upstream_task = "Undistorted"  # other option
type = "linear"
parameters = "[0,1,0]"
dilation = 5
binarize = true
threshold = 0.3

[Voxels]
upstream_mask = "Masks"
multiclass = false
voxel_size = 1.0
type = "carving"
use_colmap_poses = true
log = false

[PointCloud]
level_set_value = 1.0
background_prior= -200

[AnglesAndInternodes]
upstream_task = "TreeGraph"

[PointCloudGroundTruth]
pcd_size = 10000

[Visualization]
max_image_size = 1500
max_point_cloud_size = 10000
thumbnail_size = 150
pcd_source = "vox2pcd"
mesh_source = "delaunay"

[PointCloudEvaluation]
max_distance = 0.2

[SegmentedPointCloud]
upstream_segmentation = "Segmentation2D"

[Clean]
no_confirm = true
